version: '3.9'

services:
  postgres:
    container_name: prointro-postgres
    image: postgres
    environment:
      - POSTGRES_USER=prointro
      - POSTGRES_DB=prointro
      - POSTGRES_PASSWORD=prointro
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
volumes:
  data:
